### ISSUE TITLE
Create Audaspace nodes (like Sverchok)

### ISSUE THREAD

**Issue by mrrm92** [neXyon/audaspace#10]
Hi Nexyon.
I would like to create AudaSpace nodes with Python, like Sverchok did for geometry.
Is this possible?
I guess almost yes because, in the docs, most parameters for class methods are "standard" types (like int or float), but I can't figure out how would I connect return types such as "factory" and so.

Thanks in advance for any help.

**Comment by neXyon** [comment]
https://github.com/neXyon/audionodes ;)

**Comment by mrrm92** [comment]
You're awesome!

**Comment by mrrm92** [comment]
As far as you know, tell me, is there any limit on what can Python do in Blender?
Take this seriously.

**Comment by mrrm92** [comment]
I mean the question
