### ISSUE TITLE
Porting master back to Blender

### ISSUE THREAD

**Issue by mrrm92** [neXyon/audaspace#12]
Dear NexYon, I'd like to port Audaspace current to Blender, incorporating latest features.
This is my first "real" project, I've done really simple programming on command line until now.
I'm basically asking for help.

As a side project,  I'd like to extend your node addon, but later.

Can I rely on your help?

Thanks in advance.

**Comment by neXyon** [comment]
This has been done already.

**Comment by mrrm92** [comment]
Excuse me, I did look at the master Blender branch and I saw less source files than in this repo. Why? By the way, is the Python binding as complete?

**Comment by neXyon** [comment]
Blender 2.7x (master branch) does not support C++11, but blender 2.8 (blender2.8 branch) does, you can find it there in extern/audaspace. Even in master branch you can build blender with the latest audaspace using the WITH_SYSTEM_AUDASPACE configuration variable in cmake, but then you need the binary version of the library.
