### ISSUE TITLE
Documentation in downloadable form

### ISSUE THREAD

**Issue by mrrm92** [neXyon/audaspace#13]
Dear NeXyon, I'm going serious with Audaspace.
I'd need a comprehensive SDK documentation, better if PDF.
Is there anything like that?

Thanks in advance if you help.

**Comment by neXyon** [comment]
You could try configuring doxygen to output a pdf, I think that's possible, but there won't be more than you can find on the web.

Please stop opening issues, just send me direct mails. Issues are for bug reports mostly, not for asking simple questions to single persons.

**Comment by mrrm92** [comment]
Ok, excuse me for troubles.
Is there any link i can use for this?

**Comment by neXyon** [comment]
I don't know what you mean with this, but google is your friend?

http://lmgtfy.com/?q=audaspace+documentation
http://lmgtfy.com/?q=doxygen+pdf

**Comment by mrrm92** [comment]
Yes, it is. Sorry, my ain problem is I'm impatient, so I prefer to collect resources and then see them at once.
Again, excuse me for my abuse of Issue tracker.
Still can't find your direct contact info by the way.

**Comment by neXyon** [comment]
I think there is a function somewhere here on github to send messages? If not, you can find the mail address in the git log. ;-)

**Comment by mrrm92** [comment]
No, not AFAIK.
Is it OK if I use the address on your audaspace Dev blog?

**Comment by neXyon** [comment]
Yes, that's the one you would also find in the git log

**Comment by mrrm92** [comment]
Maybe I'm dumb, but I can't find the log.
Where am I supposed to click?
