### ISSUE TITLE
Status 

### ISSUE THREAD

**Issue by anonimo82** [neXyon/audaspace#14]
Dear Jorg, what's the status of this?
I don't know much GitHub, but I starred your repo, I guess this way I'll get notification about updates.
Am I right?

**Comment by neXyon** [comment]
Starring is only bookmarking, to get updates you need to watch it https://help.github.com/articles/watching-and-unwatching-repositories/

Don't expect too many updates though, audaspace is in maintenance currently - meaning only bug fixing, no new development.

**Comment by anonimo82** [comment]
Thanks. I'm gonna do.
