### ISSUE TITLE
How does this project track against the version in Blender (extern/audaspace)?

### ISSUE THREAD

**Issue by loren-osborn** [neXyon/audaspace#15]
This is really a documentation request. Was looking at mopping up some build warnings from Windows, and am a bit leery changing either project without knowing how changes migrate between them. I see there is only a master branch on this project, and am aware most active blender development is branched off the blender2.8 branch. Could you add a line or two in the documentation stating how these projects track each other?

- Have these projects diverged? 
    - I see the last commit indicates changes backported from blender. This suggests that either:
        - select changes are manually back-ported from blender to audaspace or
        - changes are migrated from Blender in chunks.
- Are changes here tracking a specific Blender branch (at any given time)?
     - Is the blender branch being tracked documented somewhere?
     - How about the last commit merged from that branch?
     - Is there a specific way changes from Blender are ready to be migrated?

This appears to be a rather manual process, (and given the impracticality of dealing with git submodules and subtrees, this is unsurprising.) I'm simply concerned about devoting my scarce resources to this without knowing how these changes are expected to propagate.

-Thanks

**Comment by neXyon** [comment]
As you correctly diagnosed, these two repositories are  kept in sync manually by me. You can contribute to either project, as you wish.
