### ISSUE TITLE
Is it possible to get the Blender output sound samples in Python?

### ISSUE THREAD

**Issue by snuq** [neXyon/audaspace#16]
I want to implement an audio VU meter in Blender.  To do this, I would need some way of accessing the application output audio data in realtime, is this (or will this be) possible with audaspace?
It seems like it COULD be possible at least, and this is one of my long-time Blender VSE dreams...
However, I have not managed to find anything in the documentation, or by digging through the module itself, but I am hoping I just missed it somewhere.

**Comment by neXyon** [comment]
This is currently not possible with audaspace. Unfortunately, the current architecture of audaspace doesn't easily/cleanly allow to do this, so some bigger modifications to audaspace are necessary to achieve this.
