### ISSUE TITLE
Question - Microphone input 

### ISSUE THREAD

**Issue by anonimo82** [neXyon/audaspace#18]
Hey there.
How is input from mic activated?
I saw it's possible in ReadMe.md, but I can't find the record button.

Thanks.

**Comment by neXyon** [comment]
Audaspace is a library that has support for audio recording. A software library has no buttons though... I guess what you're asking for is a button in Blender? That doesn't exist. Blender doesn't use this functionality of audaspace.

**Comment by anonimo82** [comment]
Ok, thanks.
Yes, it was about a record button in Blender.

Il giorno sab 5 gen 2019, 13:05 Jörg Müller <notifications@github.com> ha
scritto:
