### ISSUE TITLE
The .data() method of the sound object reserve a memory block and never free it.

### ISSUE THREAD

**Issue by OmarSquircleArt** [neXyon/audaspace#19]
In a Blender scene with a sound sequence, executing the following code in the text editor multiple times will eat memory until it is full:

```python
import bpy
samples = bpy.data.scenes['Scene'].sequence_editor.sequences[0].sound.factory.data()
```
This gif illustrates the problem:

![memory_issue](https://user-images.githubusercontent.com/25300994/51257806-1c869a80-19b1-11e9-9e20-fec1788e3a85.gif)

The memory is only freed when the blender instance is closed. It seems for every call to the `.data()` method, a memory block is reserved and never freed.

Is this a bug or an expected behaviour?

**Comment by neXyon** [comment]
Should be fixed now. Also in Blender, please check with a build bot build newer than this comment!

**Comment by OmarSquircleArt** [comment]
Just checked, seems to be fixed. Thanks !
