### ISSUE TITLE
Is there support to change speed of audio?

### ISSUE THREAD

**Issue by rongcuid** [neXyon/audaspace#2]
Not 'pitch', since it modifies both the pitch and speed. I was actually digging through Blender to try to hack in such feature, but it seems that Blender uses audaspace (am I correct?). I don't see anything that can change speed without affecting pitch here after a quick search through functions. Is such feature supported? Will it be supported?

**Comment by neXyon** [comment]
What you are looking for is described in this article: https://en.wikipedia.org/wiki/Audio_time-scale/pitch_modification

Basically when you change the playback speed of a sound you automatically change the pitch as well, that's what blender/audaspace is capable to do. It is described under resampling in the wikipedia article. Changing only one of them requires more advanced techniques described in the article under frequency/time domain, but these are currently not implemented.

**Comment by carldong** [comment]
Yes, I know that. I am EE Major and I know some signal processing. Could you point to the source where I may try to add this feature to? I was guessing SoftwareDevices, and add some classes in fx?

**Comment by neXyon** [comment]
Yes, you need to add an effect (fx) class to add the functionality.

The question then is how you want to be able to use it? From Blender (sequencer, speaker objects, or game engine?) or from python? Depending on that you have to add it to the sequencing classes, the C and/or Python API, usually not in the SoftwareDevice thought.

**Comment by carldong** [comment]
I did find that it may be hard to put it in Blender when I was trying to understand its architecture. I will try to add this feature in Blender. But isn't actual mixdown algorithm implemented in this library?

**Comment by neXyon** [comment]
All audio code is implemented in this library. If you tell me how you want to use it from Blender, I can give you more details. Do you want to have it as a parameter of a sequencer strip, or so?

**Comment by carldong** [comment]
I mainly want to use it in Sequencer. For now, on the right side panel, there are "Volume", "Pitch", and "Pan". My main goal is to add a "Speed" option for that. I assume that I need to hack in the RNA, DNA, operators, and add the option in UI

**Comment by neXyon** [comment]
Yeah, in this case the hirarcy is like this:

fx -> sequence classes -> C API -> sound.c (blenkernel) -> RNA -> DNA

**Comment by carldong** [comment]
OK. Is it from high level to low level? Which part should I touch inside Audaspace?

**Comment by carldong** [comment]
I am going with Phase Vocoder for now. It will take quite some time for me to prototype out the algorithm before I can put into audaspace, though. To fit in the architecture, I think I will need a custom `reader()` in my `PhaseVocoderReader` class, right?

**Comment by neXyon** [comment]
What I wrote is not exactly low to high level, but approximately the order in which the functions are called?! Implementation wise you should start on the left until you get to sound.c and then on the right also until sound.c which is the last one probably.

First you need to implement the effect class, which indeed means that you need to implement the read() function of your PhaseVocoderReader. Where are you prototyping? Matlab (that's what I used in my DSP courses at university)?

I can of course help you with any issues along the pipeline.

**Comment by carldong** [comment]
I see. I have already created a small pair of fx class, and currently I am prototyping the algorithm in Haskell (OK, I am a big functional programming fan). My prototype will be a filter program which reads from stdin to stdout. Once I get that work I may try to fit the algorithm inside the architecture. (It would be nice if I can just call the filter program, though)
