### ISSUE TITLE
Will you join us?

### ISSUE THREAD

**Issue by anonimo82** [neXyon/audaspace#20]
Hello NeXyon.
We are now a small Blender audio developers team, we're 3 people and probably we'll become 5.
Will you be the 6th?

Thanks in advance for either.

**Comment by neXyon** [comment]
That sounds awesome! May I ask what your plan is for the future? Do you want to stay in Python world or actually tackle C/C++ blender code?

**Comment by anonimo82** [comment]
We're going to use Python, mainly.
The Plug-in is almost ready, we just need to review the code, make the AddOn depending from Animation Nodes and

**Comment by neXyon** [comment]
I see. I could help with reviewing C/C++ code for Blender, but I think for anything else I don't really have time. I'm anyway in maintenance and bug fixing mode only for Blender. I wish I would have more time to develop new features...
