### ISSUE TITLE
Binaural audio rendering

### ISSUE THREAD

**Issue by AndreaMonzini** [neXyon/audaspace#29]
Hello, 
i would gently ask information about binaural audio support in Audaspace and in particular if it works in Blender 2.8x simply using 3D speakers with mono audio files and render audio  ( with HRTF ? )  in stereo. 

I can find this:
https://audaspace.github.io/bindings/sound.html

 ```
binaural()
    convolver()
    Creates a binaural sound using another sound as source. The original sound must be mono
```
about Blender i see this example:
https://github.com/blender/blender/blob/master/extern/audaspace/bindings/python/examples/binaural.py

and this patch :
https://developer.blender.org/D2716?id=9122

Anyway thank you for the fantastic Audaspace project!

Andrea

**Comment by neXyon** [comment]
Hello Andrea,

there is no binaural audio rendering support in blender yet, all you can do is write python scripts similar to the example. Proper integration into blender would require a significant amount of work that we unfortunately have no resources for at the moment.

Cheers
