### ISSUE TITLE
Record/add fades using python?

### ISSUE THREAD

**Issue by tin2tin** [neXyon/audaspace#30]
I noticed that Audaspace supports input(record?) of audio(as stated on the first page), but looking through the api, I don't see any obvious commands for doing this? https://docs.blender.org/api/current/aud.html

If it is possible to record audio with audaspace through python, is there a snippet showing how to do it somewhere?

There is this Linux-only project, which uses ffmpeg to record the audio, but it would be great if using Audaspace instead could make it cross platform: https://github.com/britalmeida/blender_addon_push_to_talk

Another thing I noticed when looking through the API is that it includes operators for doing fades. The current VSE built-in(python start up script) way to add fades is by adding keyframes, but that will make a mess out of existing keyframes. 
Those audaspace fades are they added "on top" of the f-curve animation of the volume? 
Can these fades be added through python to VSE strips?

**Comment by neXyon** [comment]
Audio recording with audaspace is very limited and currently only supported through the C++ API. Recorded samples have to be handled directly and thus this feature is not available in the Python bindings. There are currently no plans to extend functionality in this area.

Regarding adding fade in/out effects of audaspace to VSE strips in Blender: this is not possible, the VSE cannot store python objects. This would have to be implemented within Blender as  separate effect strips.

**Comment by tin2tin** [comment]
Ok. Thank you. And adding filters to vse strips through python is also out of the question right?

**Comment by neXyon** [comment]
Yes, that's what I was trying to say with the second paragraph

**Comment by tin2tin** [comment]
Ok. I don't know if you have seen this new project, which is a fork of Blender: https://github.com/ResonaBlender/resona 
The project lead's main ambition is apparently to improve the audio side of the the VSE and nodes.

**Comment by tin2tin** [comment]
On audio recording with ffmpeg on Windows in this project: https://github.com/britalmeida/blender_addon_push_to_talk 
There is some slow startup time, which makes it impossible to use it as thought, so external python libs will have to be used.

On a different note, I don't know if this is audio or video related: https://developer.blender.org/T79231
