### ISSUE TITLE
Carla and metering

### ISSUE THREAD

**Issue by tin2tin** [neXyon/audaspace#32]
You properly have considered expanding audaspace with a plugin host like this one:
https://github.com/falkTX/Carla

The ability to access all of those plugins would ex. allow for a volume meter:  
https://github.com/carlsound/AUv3-Effect-Meter

**Comment by neXyon** [comment]
I'll gladly accept a pull request, but like any bigger feature (and this certainly is one), I have no time to implement it myself, sorry.
