### ISSUE TITLE
Reverberation Support for aud.Handle

### ISSUE THREAD

**Issue by IzaZed** [neXyon/audaspace#35]
I wanted to ask if it would be possible to add reverberation support built into audaspace.

I got fairly close to a good result using multiple handles (up to 100) generated from sound.delay() offsprings, but it seems there's no way to cut the prepended silence again, so with each loop, the sounds get more and more separated.

To be honest, I don't really have any notable idea of sound programming, so I can't really tell how utopian my requests really are, but these would be amazing features:

```python
handle.reverb_volume = 1
handle.reverb_wetness = .7
handle.reverb_decay = .45
handle.reverb_delay = 60  # milliseconds
```
the position of the reverb sound would ideally be on the opposite of the original sound relative to the listener, but that's not necessary in the end

It seems from the api that most effects are handled using their own classes, like LowPass etc., that might be an option too for Reverb

A quick search gave me this: https://medium.com/the-seekers-project/coding-a-basic-reverb-algorithm-an-introduction-to-audio-programming-d5d90ad58bde, maybe that helps somehow

Looking forward to an answer to this 🙂

**Comment by neXyon** [comment]
There is support for reverberation through convolution. You will need an impulse response sound file (just google for a free one) and then you can do something like this:

```python
import aud
d = aud.Device()
s = aud.Sound('my_sound.ogg')
i_s = aud.Sound('reverb_impulse_response.wav')
i = aud.ImpulseResponse(i_s)
t = aud.ThreadPool(8)
s2 = s.resample(i_s.specs[0])
s3 = s2.convolver(i, t)
h = d.play(s3)
```

If you want to build your own reverb, you can look into the `filter` method of `aud.Sound`, but for this I recommend to have at least some knowledge about IIR filters.
