### ISSUE TITLE
Build fails with "undefined reference to `fftwf_free'"

### ISSUE THREAD

**Issue by Michael-Z-Freeman** [neXyon/audaspace#36]
Hi,

On Linux, Ubuntu Jammy ...

```
[ 70%] Linking CXX shared library libaudpulseaudio.so
[ 70%] Built target audpulseaudio
[ 71%] Building CXX object CMakeFiles/audsdl.dir/plugins/sdl/SDLDevice.cpp.o
[ 71%] Linking CXX shared library libaudsdl.so
[ 71%] Built target audsdl
[ 71%] Building CXX object CMakeFiles/audainfo.dir/demos/audainfo.cpp.o
[ 72%] Linking CXX executable audainfo
/usr/bin/ld: libaudaspace.so.1.3: undefined reference to `fftwf_free'
/usr/bin/ld: libaudaspace.so.1.3: undefined reference to `fftwf_malloc'
/usr/bin/ld: libaudaspace.so.1.3: undefined reference to `fftwf_plan_dft_c2r_1d'
/usr/bin/ld: libaudaspace.so.1.3: undefined reference to `fftwf_execute_dft_r2c'
/usr/bin/ld: libaudaspace.so.1.3: undefined reference to `fftwf_plan_dft_r2c_1d'
/usr/bin/ld: libaudaspace.so.1.3: undefined reference to `fftwf_set_timelimit'
/usr/bin/ld: libaudaspace.so.1.3: undefined reference to `fftwf_execute_dft_c2r'
/usr/bin/ld: libaudaspace.so.1.3: undefined reference to `fftwf_destroy_plan'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/audainfo.dir/build.make:99: audainfo] Error 1
make[1]: *** [CMakeFiles/Makefile2:309: CMakeFiles/audainfo.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
```

Could be related to ...

"For single precision (float) you need to link the libfftwf library, for double precision (double) you need the libfftw library. I would guess you are just linking the latter and not the former. For gcc et al the command line needs to contain -lfftw3 -lfftw3f if you want both double and single precision support."

https://stackoverflow.com/questions/27906687/fftw-library-undefined-reference-to-fftwf

ccmake reported no problems. All dependencies were installed propery AFAIK. Cheers.

**Comment by Michael-Z-Freeman** [comment]
Build error fixed with ...

`find ./ -name "link.txt" -type f -exec sed -i 's/-lfftw /-lfftw3 -lfftw3f /g' {} \; `

(from top of seperate cmake build directory).

**Comment by neXyon** [comment]
Does this patch help?

```diff
diff --git a/cmake/FindFFTW.cmake b/cmake/FindFFTW.cmake
index 6d71463..369e7b2 100644
--- a/cmake/FindFFTW.cmake
+++ b/cmake/FindFFTW.cmake
@@ -8,7 +8,7 @@
 # Use pkg-config to get hints about paths
 find_package(PkgConfig)
 if(PKG_CONFIG_FOUND)
-       pkg_check_modules(FFTW_PKGCONF fftw3)
+       pkg_check_modules(FFTW_PKGCONF fftw3f)
 endif(PKG_CONFIG_FOUND)
 
 # Include dir
@@ -19,7 +19,7 @@ find_path(FFTW_INCLUDE_DIR
 
 # Library
 find_library(FFTW_LIBRARY
-       NAMES fftw libfftw3f-3 fftw3f
+       NAMES libfftw3f-3 fftw3f fftw
        PATHS ${FFTW_PKGCONF_LIBRARY_DIRS}
 )
 
```

Note: you have to remove the FFTW variables in the cmake cache to try it.

**Comment by Michael-Z-Freeman** [comment]
Hi. I was thinking of experimenting with a game physics engine and Audaspace outside of Blender but have gone back to Audaspace in Blender. However I have  the build environment setup so will try and test this.

Should I have been using the Audaspace release from here - https://github.com/audaspace/audaspace/releases ... to build ?

**Comment by neXyon** [comment]
Either way, you can build the release or clone the repository. If you clone/update the repository now, it already includes the patch above. I'll close this for now, but if you still have problems, feel free to reopen.
