### ISSUE TITLE
Python bindings fail to install

### ISSUE THREAD

**Issue by Michael-Z-Freeman** [neXyon/audaspace#37]
make install shows ...

```
running install_egg_info
Removing usr/local/lib/python3.10/dist-packages/audaspace-1.3.0-py3.10.egg-info
Writing usr/local/lib/python3.10/dist-packages/audaspace-1.3.0-py3.10.egg-info"
```
Notice missing forwards slash before "usr" therfore package gets installed to "build/usr/local/lib/python3.10/dist-packages/" (the seperate cmake build dir).

**Comment by neXyon** [comment]
Just like #38 this depends on what your value of `CMAKE_INSTALL_PREFIX` is, since that path is used for the installation.
