### ISSUE TITLE
M_PI was not declared in this scope

### ISSUE THREAD

**Issue by parshin-pn** [neXyon/audaspace#5]
Hello.  
I'm trying to compile library on Windows using MinGW-w64 and GCC 5.4.0-seh and got this error:

```cpp
In constructor 'aud::SoftwareDevice::SoftwareHandle::SoftwareHandle(aud::SoftwareDevice*, std::shared_ptr<aud::IReader>, std::shared_ptr<aud::PitchReader>, std::shared_ptr<aud::ResampleReader>, std::shared_ptr<aud::ChannelMapperReader>, bool)':
.../deps-build/audaspace/src/project_audaspace/src/devices/SoftwareDevice.cpp:83:70: error: 'M_PI' was not declared in this scope
  m_distance_reference(1.0f), m_attenuation(1.0f), m_cone_angle_outer(M_PI), m_cone_angle_inner(M_PI), m_cone_volume_outer(0),
```
And multiple similar errors. As workaround I added to the `configure/Audaspace.h.in` this lines:

```cpp
#ifndef M_PI
#define M_PI 3.14159265358979323846
#endif
```

**Comment by parshin-pn** [comment]
Now i have this error:
```cpp
/ChannelMapperReader.cpp: In member function 'void aud::ChannelMapperReader::calculateMapping()':
.../deps-build/audaspace/src/project_audaspace/src/respec/ChannelMapperReader.cpp:171:63: error: 'M_PI_2' was not declared in this scope
    m_mapping[channel_left * m_source_channels + i] = std::cos(M_PI_2 * angle_left / angle);
```

**Comment by neXyon** [comment]
Mingw is currently not supported, so it doesn't surprise me that there are problems. A

`	add_definitions(-D_USE_MATH_DEFINES)`

properly placed (in an `if` for mingw) in CMakeLists.txt should fix these problems, but the last time I checked mingw had no proper support for the C++ thread standard library. This might have changed now. If you get everything to work, feel free to create a pull request or send a patch.

**Comment by parshin-pn** [comment]
Thanks for quick answer. I created pull request for this issue.
